// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEk4gVMcPHL8jqWKidNyvXaHqISj6xt9I',
    appId: '1:781139923697:web:d2dd762080a466942e4f50',
    messagingSenderId: '781139923697',
    projectId: 'capstone-a3e18',
    authDomain: 'capstone-a3e18.firebaseapp.com',
    storageBucket: 'capstone-a3e18.firebasestorage.app',
    measurementId: 'G-LS67B4YBQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NiZcZhNaQGs3Jc8GyuRbeBoV5UMdBdI',
    appId: '1:781139923697:android:14f6be26e27f74202e4f50',
    messagingSenderId: '781139923697',
    projectId: 'capstone-a3e18',
    storageBucket: 'capstone-a3e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbOr0tVhP6u5SLT4YAHzdfR63_JBPWadg',
    appId: '1:781139923697:ios:d682dadcd008ee652e4f50',
    messagingSenderId: '781139923697',
    projectId: 'capstone-a3e18',
    storageBucket: 'capstone-a3e18.firebasestorage.app',
    iosBundleId: 'com.example.chmrsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbOr0tVhP6u5SLT4YAHzdfR63_JBPWadg',
    appId: '1:781139923697:ios:d682dadcd008ee652e4f50',
    messagingSenderId: '781139923697',
    projectId: 'capstone-a3e18',
    storageBucket: 'capstone-a3e18.firebasestorage.app',
    iosBundleId: 'com.example.chmrsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEk4gVMcPHL8jqWKidNyvXaHqISj6xt9I',
    appId: '1:781139923697:web:38d04e48d3f988a22e4f50',
    messagingSenderId: '781139923697',
    projectId: 'capstone-a3e18',
    authDomain: 'capstone-a3e18.firebaseapp.com',
    storageBucket: 'capstone-a3e18.firebasestorage.app',
    measurementId: 'G-WJCR9LBNBL',
  );
}
